"""roles_permissions_2

Revision ID: 204b476ad9f0
Revises: 40a1f0cdfec2
Create Date: 2018-05-28 18:56:22.261880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204b476ad9f0'
down_revision = '40a1f0cdfec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.drop_index('default', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('default', 'roles', ['default'], unique=True)
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    # ### end Alembic commands ###
