"""add_PageDownField_and_body_html

Revision ID: 4fff39e09bf1
Revises: 4eb30e1c7b35
Create Date: 2018-06-03 16:48:13.936823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fff39e09bf1'
down_revision = '4eb30e1c7b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
